### ISSUE TITLE
Probably don't need type parameter in `stdscan.queryer`

### ISSUE THREAD

**Issue by DmitriyMV** [stephenafamo/scan#1]
Hey! Great project. I noticed that you define `queryer` as parameterized type. But is there any particular need for it? Judging by the usage it can be replaced with an interface because it already accepts an interface. WDYT?

**Comment by stephenafamo** [comment]
I'm not sure what you mean. Queryer contains no Types. It is the mapper that does. 

Perhaps I don't understand. Can you please explain?

**Comment by DmitriyMV** [comment]
[Here](https://github.com/stephenafamo/scan/blob/main/stdscan/stdscan.go#L47) `queryer` is always parameterized by `T` which should satisfy [Queryer constraint](https://github.com/stephenafamo/scan/blob/main/stdscan/stdscan.go#L38), but [convert](https://github.com/stephenafamo/scan/blob/main/stdscan/stdscan.go#L43) is always called with [Queryer as an interface](https://github.com/stephenafamo/scan/blob/main/stdscan/stdscan.go#L24).

**Comment by stephenafamo** [comment]
You're correct. Thank you. Fixed in the latest commit.
